### ISSUE TITLE
is `nanowallet` the name of the brew cask app?

### ISSUE THREAD

**Issue by yawhide** [nano-wallet-company/nano-wallet-desktop#19]
I ran `brew cask search nanowallet` and got this:
```
==> Matches
nanowallet
==> Remote Matches
homebrew/cask/nanowallet
```

Is nanowallet this project?

**Comment by devinus** [comment]
Negative.

**Comment by yawhide** [comment]
Is adding this app to brew something on your roadmap?

**Comment by canted** [comment]
the nanowallet on cask is for NEM https://github.com/NemProject/NanoWallet
