### ISSUE TITLE
Source build:  wallet creation and  seed import hanging

### ISSUE THREAD

**Issue by stefonarch** [nano-wallet-company/nano-wallet-desktop#22]
As title, compiled on arch linux.
Creating wallet:
![schermata-21-21-22-42](https://user-images.githubusercontent.com/10681413/41746435-9af89130-75aa-11e8-96d0-439437286029.png)
Importing seed:
![schermata-21-21-26-13](https://user-images.githubusercontent.com/10681413/41746461-b1b1b1fe-75aa-11e8-85e2-578633bddb94.png)

**Comment by devinus** [comment]
@stefonarch Take a look at the network tab. What are the requests/responses you're seeing?

**Comment by robbsolter** [comment]
I get the same thing when built on OSX, the app is trying to connect to http://localhost:55000/ but I don't have anything on that port...

**Comment by stefonarch** [comment]
![schermata-22-10-07-52](https://user-images.githubusercontent.com/10681413/41765372-27597da2-7604-11e8-8a44-9e57e8e6bfeb.png)

**Comment by devinus** [comment]
This should be fixed from v1.0.0.rc.2 and up.

**Comment by robbsolter** [comment]
I still see the same thing after cloning the latest master branch, which commit is the one that should fix it?

Its like the RPC server isnt starting or something...

**Comment by robbsolter** [comment]
Oh it works correctly if I do `yarn electron:start`

If I do `yarn start` I get the errors above
