### ISSUE TITLE
Horizontal scrolling through accounts

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#25]
Currently cannot scroll horizontally through accounts using CTRL + MOUSEWHEEL

Not very desktop friendly or intuitive if one has to click on the accounts and drag left and right.

As soon as have more than 3-4 accounts this is an issue.

**Comment by kennedybaird** [comment]
https://github.com/kenwheeler/slick/issues/122

This seems to be a lot more complicated than I first thought.

Would you like me to pursue it more @devinus?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
