### ISSUE TITLE
Copying seed in "Backup Seed" screen is confusing

### ISSUE THREAD

**Issue by miki151** [nano-wallet-company/nano-wallet-desktop#28]
We have the seed mnemonic and below that buttons "Copy seed" and "Download". The intuition is that "Copy seed" copies the mnemonic because it's just below it. I suggest having a "Copy mnemonic" button, below that display the seed in another text area with a "Copy seed" button.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
