### ISSUE TITLE
No way to go back from "Create New Wallet" screen to wallet password screen

### ISSUE THREAD

**Issue by miki151** [nano-wallet-company/nano-wallet-desktop#32]
If instead of entering password to unlock wallet I click "Create New Wallet", there is no way to go back to entering password, I have to restart the app.

**Comment by kennedybaird** [comment]
For the moment you can use ALT + arrow keys for dev purposes.

I feel that being presented with a login screen, with a password field and a button saying create new wallet that links to a second screen which then asks about creating or importing doesn't make so much sense to me.

![image](https://user-images.githubusercontent.com/20593811/41905046-339548b8-7964-11e8-85e6-527a634b32dc.png)
This is a smoother UI experience in my mind.

Can we pass a param to setup.index of the intended final destination if it is only checking the node, so can bypass an additional, unnecessary screen?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
