### ISSUE TITLE
Exporting wallet seed via QR code

### ISSUE THREAD

**Issue by miki151** [nano-wallet-company/nano-wallet-desktop#33]
It seems like the android wallet can import a seed from a QR code. It would be very convenient if the desktop wallet could export it that way.

**Comment by kennedybaird** [comment]
Do we want this in settings modal @devinus?

**Comment by pRizz** [comment]
There is now a QR code on the main screen for your address

**Comment by kennedybaird** [comment]
This is for the wallet seed, not the address seed.

**Comment by qwahzi** [comment]
If this is implemented, I would suggest requiring password auth again before displaying the seed QR code. Similar to how Blockhain.info does it.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
