### ISSUE TITLE
Sending is broken (Linux)

### ISSUE THREAD

**Issue by miki151** [nano-wallet-company/nano-wallet-desktop#34]
Choosing MAX amount makes the send button inactive, as if there aren't enough funds. (btw, difference between active/inactive send button is not visible enough)

Choosing a smaller amount makes the button active, but clicking it doesn't do anything.

Eventually the "send" menu exits back to the main page by itself. No transaction was made.

**Comment by devinus** [comment]
This should be fixed from v1.0.0.rc.2 and up.
