### ISSUE TITLE
Add warning about deleting old wallet when creating a new one

### ISSUE THREAD

**Issue by stefonarch** [nano-wallet-company/nano-wallet-desktop#38]
From login it's possible to create a new wallet and no information about the deleting  of the existing  wallet is displayed. This will hurt somebody sooner or later. 
So add a second confirmation dialog 

> This will delete your existing wallet, make sure it doesn't contain funds anymore or that you have a verified backup copy of the seed

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
