### ISSUE TITLE
Only generic icon on taskbar

### ISSUE THREAD

**Issue by stefonarch** [nano-wallet-company/nano-wallet-desktop#39]
![schermata-25-15-11-21](https://user-images.githubusercontent.com/10681413/41852017-2dac4f62-788a-11e8-844e-5c8b948f71b7.png)

**Comment by kennedybaird** [comment]
What OS are you using?

No issue on Kubuntu 18.04

But icon in top left of active window shows default electron icon.

Looking at `ember-electron/main.js` shows that the icon is properly passed through to electron BrowserWindow instance

**Comment by stefonarch** [comment]
It's arch linux/LQXt

**Comment by stefonarch** [comment]
Hm also Ubuntu in vbox. So it's somehow related to LXQt maybe.
