### ISSUE TITLE
mnemonic be available in settings like seed

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#41]
**Is your feature request related to a problem? Please describe.**
Should mnemonic be available in settings like seed?

**Describe the solution you'd like**
A second field, hidden by default, with mnemonic available.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
