### ISSUE TITLE
Individual account settings doesn't show full address

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#42]
**Describe the bug**
Account settings does not show full address.

**To Reproduce**
1. Click on account settings

**Expected behavior**
Should show full account name, bonus it would be a copy field

**Platform (please complete the following information):**
All (assumed) - Linux

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
