### ISSUE TITLE
Wider modal for settings

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#43]
**Is your feature request related to a problem? Please describe.**
Bootstrap has a wider modal option. As the seed + representative currently don't fit at the native resolution of the app a wider modal is needed.

When going full screen the modal size stays small and still means you can't see end of seed or rep.

**Describe the solution you'd like**
Bootstraps wider modal

**Describe alternatives you've considered**
A reworking of the settings "page" might be better, but could be supported simply by the wider modal

**Comment by devinus** [comment]
Closed by https://github.com/nano-wallet-company/nano-wallet-desktop/pull/47.
