### ISSUE TITLE
Require current password to change password

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#48]
**Is your feature request related to a problem? Please describe.**
I feel that due to people being likely to leave their client open on their PC, it is probably prudent to require current password before changing via the settings page.

**Describe the solution you'd like**
Require current password before change passwod.

**Comment by Shrey33** [comment]
@kennedybaird can you provide some screen shots and reproduction steps ?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
