### ISSUE TITLE
Typos in translation into Russian

### ISSUE THREAD

**Issue by KedrinWelodon** [nano-wallet-company/nano-wallet-desktop#54]
Fix in:
instructions:  "кошешелек" to "кошелек"
data: "данные" to "данных"
send: "Отослать" to "ОТПРАВИТЬ"
representativeChangeFailed: "неудалась" to "не удалась"

**Comment by EvertonMelo** [comment]
@KedrinWelodon  thank you for your suggestions.
after apply #61 close that issue. 

Благодарю вас.
