### ISSUE TITLE
Copy address still copies xrb_ address, not new nano_

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#56]
**Describe the bug**
Copy field was displaying new nano_ address but then would copy xrb_ address

**To Reproduce**
Click copy on any account, flashmessage will show xrb_ address

**Expected behavior**
Should show nano_ address as is displayed in the copy field

**Comment by pRizz** [comment]
This seems to be fixed in the latest release

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
