### ISSUE TITLE
Amounts over 1000 seem to be considered invalid

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#62]
**Describe the bug**
It seems any amount over 999 (1000+) triggers an invalid amount error, even if the selected account has enough funds: `Invalid amount`

Amounts 999 and below react normally - triggering the error `Amount is greater than total account balance`

**To Reproduce**
1. Try to send from an account with more than 1000 balance.

**Platform (please complete the following information):**
 - Linux (Beta network, in Chrome)
 - 1.0.3 (master)

**Additional context**
Another note is that changing the account doesn't seem to trigger a refresh of the input field / re-check.

So having 999 in the send field, then changing to an account with only 300 in it doesn't trigger any update / warning. It does change the max value for the input field, so when focusing again it requires a change to register that there is an issue.

**Comment by kennedybaird** [comment]
It is line 33 of `account-send/component.js`

Removing the `formatNumber` for the amount solves the problem.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
