### ISSUE TITLE
Add this to the Mac App Store

### ISSUE THREAD

**Issue by pRizz** [nano-wallet-company/nano-wallet-desktop#79]
**Is your feature request related to a problem? Please describe.**
As a Mac Desktop user, it would be nice to download the Nano Desktop Wallet from the official Mac App Store.

**Describe the solution you'd like**
Provide the wallet from the Mac App Store

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
