### ISSUE TITLE
Uninstalling should delete and/or rename the AppData folders

### ISSUE THREAD

**Issue by qwahzi** [nano-wallet-company/nano-wallet-desktop#83]
**Is your feature request related to a problem? Please describe.**
I've run into multiple situations where the wallet would not open and/or sync (usually after an upgrade), so I then decide to reinstall. However, running the Windows uninstaller is not enough - you also have to manually delete or rename the Nano/RaiBlocks folders in AppData before reinstalling (otherwise the issue persists). After doing that and installing/syncing from scratch, everything works correctly.

**Describe the solution you'd like**

- When uninstalling, have a checkbox to remove all saved preference files/configs

- When installing, have a checkbox to use existing preference files/configs or to start from scratch

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
