### ISSUE TITLE
On Windows with non-UTF codepage, fails to start if current user name contains non-ASCII characters.

### ISSUE THREAD

**Issue by catenocrypt** [nano-wallet-company/nano-wallet-desktop#84]
Preconditions: Windows OS with non-UTF codepage (e.g. Hungarian language Windows), current user name contains non-ASCII characters (e.g. 'józsef').

Symptom: Wallet fails to start, it is stuck in loader animation. No info in logs.

Analysis: Due to LMDB / rai_node issue, in this case the DB file cannot be opened. The node does not handle this nicely, it quits, without any error in logs or on cout/cerr, or result code. The wallet is stuck waiting for the node to start up.

Solution available in LMDB.

See:
https://github.com/nanocurrency/lmdb/pull/2
https://github.com/mikroncoin/mikron_wallet/issues/8

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
