### ISSUE TITLE
Electron packaging

### ISSUE THREAD

**Issue by imtiyazs** [nano-wallet-company/nano-wallet-desktop#92]
Can anybody provide me electron package command to build for windows and MacOS? I built the source but it gives me module error. I guess I am not doing it correctly.
Please let me know the steps to build the electron application from source.

**Comment by zhyatt** [comment]
@devinus Is this something you have available?

**Comment by devinus** [comment]
@imtiyazs It depends on which environment. For a build as close to possible as release, you can use something like this on macOS:

```sh-session
yarn cross-env NODE_ENV=production ember electron:make -e production
```

**Comment by imtiyazs** [comment]
Thanks for the reply @devinus . I tried running the command. It didnt fail, but it is stuck on below output.
![1](https://user-images.githubusercontent.com/31210898/54551326-e7f48680-49d3-11e9-8523-d00117a78815.png)

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
