### ISSUE TITLE
Nano Withdrawal Bug

### ISSUE THREAD

**Issue by jzstern** [nano-wallet-company/nano-wallet-desktop#95]
Tried to withdraw my Nano from Nano Wallet Desktop, and while my balance shows 0 in the wallet the tokens didn't show up in the wallet I was sending to. Checked the Nanode block explorer and it appears the Nano never left my wallet, despite display a balance of 0.

You can view my wallet history [here](https://www.nanode.co/account/nano_1p5d3ji9o53n5p6j9jyu44p59nmi8guwkyxi4h7gcqkwshqwikjrcosnjh3n) (I don't mind sharing this info for the sake of fixing this bug)

<img width="1278" alt="Screen Shot 2019-07-13 at 2 50 19 PM" src="https://user-images.githubusercontent.com/9055087/61176401-90c78280-a57d-11e9-83a6-9e472aeba167.png">

Platform:
 - OS: macOS Mojave 
 - Version 10.14.3

Haven't had any trouble sending/receiving from this wallet in the past.

**Comment by jzstern** [comment]
Any update on this?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
