### ISSUE TITLE
Uncaught Error:  Expected to find: 'service:settings

### ISSUE THREAD

**Issue by imtiyazs** [nano-wallet-company/nano-wallet-desktop#96]
The source code worked perfect back before a month. But now it is giving me this issue.
Does anybody know how to fix this issue ? 

Please ignore red spots, I have renamed the repo but it is a fork of nano wallet.

![Capture](https://user-images.githubusercontent.com/31210898/61555159-5463bd00-aa7c-11e9-94be-4550938d1351.JPG)

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
