### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be one of type Array, Buffer, or Uint8Array. Received type string

### ISSUE THREAD

**Issue by imtiyazs** [nano-wallet-company/nano-wallet-desktop#98]
**Screenshots**
![Untitled](https://user-images.githubusercontent.com/31210898/62420346-4afa6780-b6ae-11e9-9826-357739ea2111.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.0

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
